training:
  batch_size : 8
  loader_workers : 8
  pin_memory : True
  prefetch_factor : 2
  gradient_accumulation_steps : 2
  mixed_precision : 'fp16' # 'no', 'bf16'
  start_step : 0
  p1_total_step : 140000
  p2_total_step : 140000
  l1_lambda : 3.0
  id_lambda : 3.0
  lpips_lambda : 30.0
  content_lambda : 20.0
  loss_type : 'basic'
  lpips_type : 'alex'
  lpips_model_path : ''
  id_model_path : '/workspace/gan/3D-FM-GAN/pretraiend/model_ir_se50.pth'
  scheme: 'from_pretrained' # 'resume', 'from_pretrained', 'scratch'
  from_pretrained_path : '/workspace/gan/3D-FM-GAN/pretraiend/550000.pt'
  resume_path : null

eval:
  batch_size : 64
  pin_memory : True
  loader_workers : 8
  prefetch_factor : 2
  
model:
  wplus_num_layers : 50
  output_size : 256
  input_size : 256
  disc : True

dataset:
  root : '/workspace/gan/3D-FM-GAN/data'
  recon1 :
    sub_dir : 'ffhq'
    crop : False
    random_flip : True
    range : [0, 65000]
    resize : 256
  recon2 :
    sub_dir : 'syn_data'
    crop : False
    random_flip : True  
    range : [0, 70000]
  disen :
    sub_dir : 'syn_data'
    crop : False
    random_flip : True
    resize : 256
  eval_fake : 
    sub_dir : 'ffhq'
    crop : False
    random_flip : False
    range : [65000, 70000]
  eval_real : 
    sub_dir : 'ffhq'
    crop : False
    random_flip : False
    range : [65000, 70000]

optimizer:
  use_8bit_adam : True
  lr1 : 0.0001
  lr2 : 0.001
  beta1 : 0
  beta2 : 0.999

ckpt_interval : 60
log_interval : 30
evaluation_interval : 30
seed : 77
with_tracking : True
exp_name : 'exp1'
# logging_path : '/workspace/gan/3D-FM-GAN/logging'
eval_metrics : ['fid50k'] # 'fid50k', 'pr' ,..
eval_during_training : True
eval_backbone : 'InceptionV3_tf' # TODO : DINO_torch
num_gpus : 8
num_generation : 10
post_resizer : 'friendly'